# Название книги
title: О книге
author: "Назаров Руслан"

# Ссылка на репозиторий
repository:
  url: https://github.com/Ruslan-Nazarov/handbook_Languages
  path_to_book: ""
  branch: main

# Настройки исполнения
execute:
  execute_notebooks: off

# Настройки оформления
html:
  extra_css:
    - _static/custom.css
  analytics:
    google_analytics_id: "G-L9BCXQ2FD1"
  logo: logo.png
  favicon: logo.png
  navbar_brand_box_2:          # В некоторых версиях помогает этот блок
    logo_only: true

# Расширения
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - amsmath

# Настройки автора и копирайта
author: "Назаров Руслан"
copyright: "2026"  # Или "2022–2026", если проект длительный

sphinx:
  config:
    html_theme_options:
      logo_only: true








